@startuml erd

hide circle

skinparam linetype ortho

Entity User {
    * id
    --
    * name: String
    * password: String
}


Entity Ride {
  * id
  --
  * driverID: <<FK>>
  * start: string
  * destination: string
  * price: decimal
  * departure: DateTime
  driverNote: string
}

Entity Review {
    * id
    ---
    * userId: <<FK>>
    * authorId: <<FK>>
    * score: int
    reviewText: string
}

Entity UserRide {
    * id
    --
    * passangerId: <<FK>>
    * rideId: <<FK>>
    * passangerCount: int
    note: string
    accepted: bool
}


User ||--o{ Ride
User ||--o{ Review
Ride ||--o{ UserRide

@enduml